parcelParameter:
    color :
      - "Coral"
      - "LightSalmon"
      - "gold"
      - "yellow"
    barcode:
      - "92200"
      - "94360"
      - '77420'
      - "55100"
    confBay:
        'bay':
            - 'V'
            - 'W'
            - 'Y'
            - 'X'
        'postCode':
            - '92200'
            - '94360'
            - '77420'
            - '55100'
       
    
